var editor1 = new TINY.editor.edit('editor1', {
	id : 'tinyeditor1',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor1',
});
var editor2 = new TINY.editor.edit('editor2', {
	id : 'tinyeditor2',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor2',
});
var editor3 = new TINY.editor.edit('editor3', {
	id : 'tinyeditor3',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor3',
});
var editor4 = new TINY.editor.edit('editor4', {
	id : 'tinyeditor4',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor4',
});
var editor5 = new TINY.editor.edit('editor5', {
	id : 'tinyeditor5',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor5',
});
var editor6 = new TINY.editor.edit('editor6', {
	id : 'tinyeditor6',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor6',
});
var editor7 = new TINY.editor.edit('editor7', {
	id : 'tinyeditor7',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor7',
});