var editor = new TINY.editor.edit('editor', {
	id : 'tinyeditor',
	width : 500,
	height : 125,
	cssclass : 'tinyeditor',
	controlclass : 'tinyeditor-control',
	rowclass : 'tinyeditor-header',
	dividerclass : 'tinyeditor-divider',
	controls : [ 'bold', 'italic', 'underline', 'strikethrough', '|',
			'subscript', 'superscript', '|', 'orderedlist', 'unorderedlist',
			'|', 'outdent', 'indent', '|', 'leftalign', 'centeralign',
			'rightalign', 'blockjustify', '|', 'unformat', '|', 'undo', 'redo',
			'n', '|', 'image', 'hr' ],
	footer : false,
	fonts : [ 'Verdana', 'Arial', 'Georgia', 'Trebuchet MS' ],
	xhtml : true,
	cssfile : 'custom.css',
	bodyid : 'editor',
});
